### ISSUE TITLE
Exception after copy/pasting OAuth links

### ISSUE THREAD

**Issue by jvolker** [bretwalker/Rdio2Spotify#4]
Thanks for creating this!

I followed the instructions in the readme. But after copying the OAuth links to the browser and seeing the following there …

```
Code received successfully

Please look back at the terminal.
```

… I got this error in Terminal:

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 59767)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "main.py", line 28, in do_GET
    Handler.code = urlparse(s.path).query.split('=')[1]
IndexError: list index out of range
----------------------------------------
Traceback (most recent call last):
  File "main.py", line 440, in <module>
    rdio_session, spotify_session = get_sessions()
  File "main.py", line 81, in get_sessions
    decoder=json.loads)
  File "/Library/Python/2.7/site-packages/rauth/service.py", line 556, in get_auth_session
    session = self.get_session(self.get_access_token(method, **kwargs))
  File "/Library/Python/2.7/site-packages/rauth/service.py", line 542, in get_access_token
    access_token, = process_token_request(r, decoder, key)
  File "/Library/Python/2.7/site-packages/rauth/service.py", line 24, in process_token_request
    raise KeyError(PROCESS_TOKEN_ERROR.format(key=bad_key, raw=r.content))
KeyError: 'Decoder failed to handle access_token with data as returned by provider. A different decoder may be needed. Provider returned: {"error":"invalid_grant","error_description":"Invalid authorization code"}'
```

I'm trying to run this on OS-X 10.10.5.

Thanks!

**Comment by bretwalker** [comment]
Can you let me know if this still happens with the latest code?
